import type { Metadata }  from 'next'
import { Inter }          from 'next/font/google'
import { notFound }       from "next/navigation";


const inter   = Inter({ subsets: ['latin'] })
const locales = ['vi', 'en'];

type Props    = {
  children    : React.ReactNode;
  params      : {locale: string};
};

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

function generateStaticParams() {
  return [{ locale: "vi" }, { locale: "en" }];
}

async function LocaleLayout({children, params : { locale }}: Props) {
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
          {children}
      </body>
    </html>
  );
}

export default LocaleLayout;
export {
    metadata, 
    generateStaticParams 
}